### PR TITLE
Bindgen and build bundled 

### PR DESCRIPTION
**Pull request by revmischa**
* Use bindgen to automatically generate bindings for all SDL symbols (we don't need to spell them all out by hand)
* Use cmake to build libsdl3 automatically
* Use git submodule to fetch c-sdl3 instead of including all the files in this repo
* Heavily based on https://github.com/Rust-SDL2/rust-sdl2/tree/master/sdl2-sys

These work for me on linux:
```
cargo build -F bindgen -F bundled
```
and
```
cargo build -F bindgen -F pkg-config
```

I think we can start using libsdl3 today. If the interface changes, simply updating the submodule version and re-running bindgen should get the new goodies. No need to wait.

### CODE REVIEW

**Comment by revmischa** [comment]
Actually for sanity I suggest we adopt the approach used by Rust-SDL2 and include sdl3-sys in the same repo: https://github.com/Rust-SDL2/rust-sdl2/tree/master/sdl2-sys

I'm trying that out here https://github.com/revmischa/sdl3-rs/tree/master/sdl3-sys

I would like to publish a new version of sdl3-sys from there if you are okay with it.

**Comment by Lokathor** [comment]
This is a very large and unexpected PR, so allow me a moment to try and process this.

My initial thought is that, based on experience in `fermium`, in the long term spelling things out by hand gives better results than bindgen. I suppose that using bindgen temporarily and/or optionally while SDL3 is in development is fine enough to get started.

For feature names, some of them use underscores and some of them use dashes. Let's be consistent. I'm leaning towards "always spell it with underscore".

Also, for the four "add on" SDL3 packages, let's call that "sdl3_image" and "sdl3_ttf" and such. The reason being that `gfx` and `image` are already real packages in the Rust ecosystem and we should avoid any confusion.

I know that the current `license` entry in Cargo.toml only says `Zlib` but before we start adding a lot of code let's make it `Zlib OR Apache-2.0 OR MIT`. A lot of rust folks really love that `Apache-2.0 OR MIT` part after all.

I won't be back at my Windows computer util later today, but the I can double check the Windows build. I suppose we should set up different CI configurations for all these build variations soon.

In terms of moving the repo, If this repo having the C SDL3 files as a submodule is fine, can't the `sdl3` crate have `sdl3-sys` as a submodule also if it needs to? I genuinely have never used git submodules myself, and so i don't understand the pros and cons.

If you think that SDL3 has lowered their churn rate enough to get people using it then I'm happy to focus on this crate more and try to get something out and usable soon. It's just that last I read the issue tracker they still planned to do things like completely overhaul their audio API.

**Comment by revmischa** [comment]
Okay, I'm all for fixing it up, making the casing consistent, and whatnot. I agree the add-ons should be prefixed with sdl3_*.

The sdl3 crate could certainly use this repo as a submodule. Submodules do tend to be great conceptually and annoying in practice. Since sdl3-rs is tightly coupled to sdl3-sys and the existing sdl2-rs repo keeps them both in the same repo I thought it makes sense to continue that.
After poking a bit at all this, I realized it makes a ton more sense to start with bindgen and [fork the sdl2-rs repo and update it for sdl3](https://github.com/revmischa/sdl3-rs) which is what I'm doing right now. And we can make whatever changes we want to the fork. But I really suggest we start from the existing sdl2-rs setup and improve it incrementally rather than a complete rewrite without bindgen. Unless you happen to be a robot and have a zillion hours to dedicate to implementing all of the FFI bindings by hand.

**Comment by Lokathor** [comment]
Everything that's currently in `fermium` I wrote by hand, because I usually have that kind of time. I'll admit that `fermium` does not 100% of the SDL2 API, but it does cover "basically everything you'd reasonably want". My experience when *using* `fermium` was that in particular having the right docs in the Rust code lets RA and rustdoc show useful docs without having to try and use the SDL2 wiki (which is not so great). Since bindgen didn't handle transferring docs over that well at all (at the time, maybe it got better?), I ended up just doing a few include files per evening while watching a show until it was all done, and I've been quite happy with the crate since.

all that said, I'm totally fine putting any handwritten stuff off until **much** later, once C-SDL3 is fully released and set in stone for at least another 10 years or however long.

I'm slightly hesitant to copy the existing sdl2 stuff *too* much because honestly they give too many controls. I think it confuses users. I know it confuses me when I tried to use it. It does work as a starting point though, and then adjust as we go like you say.

**Pull request merged**
